routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Cv\CvController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Offre\OffreController;
use App\Http\Controllers\Profile\ProfileController;
use App\Http\Controllers\Secteur\SecteurController;
use App\Http\Controllers\Candidat\CandidatController;
use App\Http\Controllers\Parametre\ParametreController;
use App\Http\Controllers\Recruteur\RecruteurController;
use App\Http\Controllers\Conversation\ConversationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'admin.auth.login')->name('login');
        Route::post('/check', [AdminController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:admin', 'PreventBackHistory'])->group(function () {

        Route::controller(OffreController::class)->group(function () {
            Route::get('/offres', 'index')->name('auth.offres');
            Route::get('/offres/favories', 'offresFavories')->name('auth.offres.favories');
            Route::get('/offres/mes-offres', 'mes_offres')->name('auth.offres.mes-offres');
            Route::get('/offres/create', 'create')->name('auth.offres.create');
            Route::post('/offres/store', 'store')->name('auth.offres.store');
            Route::get('/offres/{offre}/postulants', 'postulants')->name('auth.offres.postulants');
            Route::get('/offres/{offre}', 'show')->name('auth.offres.show');
            Route::put('/offres/{offre}', 'update')->name('auth.offres.update');
            Route::delete('/offres/{offre}', 'destroy')->name('auth.offres.destroy');
            Route::get('/offres/{offre}/edit', 'edit')->name('auth.offres.edit');
        });

        Route::controller(ConversationController::class)->group(function () {
            Route::get('/conversations', 'index')->name('auth.conversations');
            Route::get('/conversations/{conversation}', 'show')->name('auth.conversations.show');
        });

        Route::controller(SecteurController::class)->group(function () {
            Route::get('/secteurs', 'index')->name('auth.secteurs');
            Route::get('/secteurs/create', 'create')->name('auth.secteurs.create');
            Route::post('/secteurs/store', 'store')->name('auth.secteurs.store');
            Route::get('/secteurs/edit/{secteur}', 'edit')->name('auth.secteurs.edit');
            Route::put('/secteurs/update/{secteur}', 'update')->name('auth.secteurs.update');
            Route::delete('/secteurs/delete/{secteur}', 'destroy')->name('auth.secteurs.destroy');
        });

        Route::controller(CvController::class)->group(function () {
            Route::get('/cvs', 'index')->name('auth.cvs');
            Route::get('/cvs/create', 'create')->name('auth.cvs.create');
            Route::post('/cvs/store', 'store')->name('auth.cvs.store');
            Route::get('/cvs/show/{cv}', 'show')->name('auth.cvs.show');
            Route::delete('/cvs/delete{cv}', 'destroy')->name('auth.cvs.destroy');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });


        Route::controller(AdminController::class)->group(function() {
            Route::get('/candidats', 'candidats')->name('auth.candidats');
            Route::get('/recruteurs', 'recruteurs')->name('auth.recruteurs');
            Route::delete('/candidats/{user}', 'destroyUser')->name('auth.candidats.destroy');
            Route::delete('/recruteurs/{user}', 'destroyUser')->name('auth.recruteurs.destroy');
            // Route::get('/moi/profils', 'profils')->name('auth.profils');
            Route::post('/logout', 'logout')->name('auth.logout');
        });

        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

    });
});

Route::prefix('recruteur')->name('recruteur.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'recruteur.auth.login')->name('login');
        Route::view('/register', 'recruteur.auth.register')->name('register');
        Route::post('/register', [RecruteurController::class, 'storeRegister'])->name('store.register');
        Route::post('/check', [RecruteurController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:recruteur', 'PreventBackHistory'])->group(function () {

        Route::controller(OffreController::class)->group(function () {
            // Route::get('/offres', 'index')->name('auth.offres');
            // Route::get('/offres/favories', 'offresFavories')->name('auth.offres.favories');
            Route::get('/offres/mes-offres', 'mes_offres')->name('auth.offres.mes-offres');
            Route::get('/offres/create', 'create')->name('auth.offres.create');
            Route::post('/offres/store', 'store')->name('auth.offres.store');
            Route::get('/offres/{offre}/postulants', 'postulants')->name('auth.offres.postulants');
            Route::get('/offres/{offre}', 'show')->name('auth.offres.show');
            Route::put('/offres/{offre}', 'update')->name('auth.offres.update');
            Route::get('/offres/{offre}/edit', 'edit')->name('auth.offres.edit');
            Route::delete('/offres/{offre}', 'destroy')->name('auth.offres.destroy');
        });


        Route::controller(ConversationController::class)->group(function () {
            Route::get('/conversations', 'index')->name('auth.conversations');
            Route::get('/conversations/{conversation}', 'show')->name('auth.conversations.show');
        });

        Route::controller(CvController::class)->group(function () {
            Route::get('/cvs', 'index')->name('auth.cvs');
            Route::get('/cvs/create', 'create')->name('auth.cvs.create');
            Route::post('/cvs/store', 'store')->name('auth.cvs.store');
            Route::get('/cvs/show/{cv}', 'show')->name('auth.cvs.show');
            Route::delete('/cvs/delete{cv}', 'destroy')->name('auth.cvs.destroy');
        });


        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::patch('moi/profils/update-additional', 'updateAdditional')->name('auth.profils.updateAdditional');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });

        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::patch('moi/profils/update-additional', 'updateAdditional')->name('auth.profils.updateAdditional');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });

        Route::controller(RecruteurController::class)->group(function() {
            // Route::get('/moi/profils', 'profils')->name('auth.profils');
            // Route::get('/moi/parametres', 'parametres')->name('auth.parametres');
            Route::post('/logout', 'logout')->name('auth.logout');
        });
    });
});

Route::prefix('candidat')->name('candidat.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'candidat.auth.login')->name('login');
        Route::view('/register', 'candidat.auth.register')->name('register');
        Route::post('/register', [CandidatController::class, 'storeRegister'])->name('store.register');
        Route::post('/check', [CandidatController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:candidat', 'PreventBackHistory'])->group(function () {

app/Http/Controllers/Parametre/ParametreController.php
<?php

namespace App\Http\Controllers\Parametre;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProfileUpdateRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;

class ParametreController extends Controller
{
    /**
     * Display the user's profile form.
     */
    public function edit() {
        if (request()->routeIs('admin.auth.parametres')) {
            return view('admin.parametre.edit');
        }

        if (request()->routeIs('recruteur.auth.parametres')) {
            return view('recruteur.parametre.edit');
        }

        return view('candidat.parametre.edit');
    }

    /**
     * Update the user's profile information.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        $request->validate([
            'nom' => 'required',
            'prenom' => 'required',
            'telephone' => 'required',
            'adresse' => 'required',
            'ville' => 'required',
            'image' => 'image|mimes:jpeg,png,jpg|max:2048',
        ]);
        $user = $request->user();
        $user->nom = $request->input('nom');
        $user->prenom = $request->input('prenom');
        $user->telephone = $request->input('telephone');
        $user->adresse = $request->input('adresse');
        $user->email = $request->input('email');
        $user->ville = $request->input('ville');

        if ($request->file('image')) {
            $image_file = $request->file('image')->hashName();
            $path_image = $request->file('image')->storeAs(
                'images_profil',
                $image_file,
                'public'
            );

            $user->image = $path_image;
        }
    
        if ($request->user()->isDirty('email')) {
            $user->email_verified_at = null;
        }
    
        $user->save();

        switch ($user->role) {
            case 'admin':
                return redirect()->route('admin.auth.profils')->with('success', 'Mise à jour du profil réussie !');
            case 'recruteur':
                return redirect()->route('recruteur.auth.profils')->with('success', 'Mise à jour du profil réussie !');
            
            default:
            return redirect()->route('candidat.auth.profils')->with('success', 'Mise à jour du profil réussie !');
        }

    
    }
    
    /**
     * Delete the user's account.
     */
    public function destroy(Request $request): RedirectResponse
    {
        $request->validateWithBag('userDeletion', [
            'password' => ['required', 'current_password'],
        ]);

        $user = $request->user();

        Auth::logout();

        $user->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return Redirect::to('/');
    }
}

resources/views/recruteur/parametre/partials/delete-user-form.blade.php
<section class="space-y-6">
     <header>
         <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
             {{ __('Supprimer le compte') }}
         </h2>
 
         <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
             {{ __('Une fois votre compte supprimé, toutes ses ressources et données seront définitivement supprimées. Avant de supprimer votre compte, veuillez télécharger les données ou informations que vous souhaitez conserver.') }}
         </p>
     </header>
 
     <x-danger-button
         x-data=""
         x-on:click.prevent="$dispatch('open-modal', 'confirm-user-deletion')"
     >{{ __('Supprimer le compte') }}</x-danger-button>
 
     <x-modal name="confirm-user-deletion" :show="$errors->userDeletion->isNotEmpty()" focusable>
         <form method="post" action="{{ route('recruteur.parametre.destroy') }}" class="p-6">
             @csrf
             @method('delete')
 
             <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
                 {{ __('Êtes-vous sûr de vouloir supprimer votre compte?') }}
             </h2>
 
             <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
                 {{ __('Une fois votre compte supprimé, toutes ses ressources et données seront définitivement supprimées. Veuillez saisir votre mot de passe pour confirmer que vous souhaitez supprimer définitivement votre compte.') }}
             </p>
 
             <div class="mt-6">
                 <x-input-label for="password" value="{{ __('Password') }}" class="sr-only" />
 
                 <x-text-input
                     id="password"
                     name="password"
                     type="password"
                     class="mt-1 block w-3/4"
                     placeholder="{{ __('Mot de passe') }}"
                 />
 
                 <x-input-error :messages="$errors->userDeletion->get('password')" class="mt-2" />
             </div>
 
             <div class="mt-6 flex justify-end">
                 <x-secondary-button x-on:click="$dispatch('close')">
                     {{ __('Annuler') }}
                 </x-secondary-button>
 
                 <x-danger-button class="ml-3">
                     {{ __('Supprimer le compte') }}
                 </x-danger-button>
             </div>
         </form>
     </x-modal>
 </section>
 

resources/views/recruteur/parametre/partials/update-password-form.blade.php
<section>
     <header>
         <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
             {{ __('Mettre à jour le mot de passe') }}
         </h2>
 
         <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
             {{ __('Assurez-vous que votre compte utilise un mot de passe long et aléatoire pour rester en sécurité.') }}
         </p>
     </header>
     
 
    @if (session('error'))
        <div class="text-red-500" role="alert">
            {{ session('error') }}
        </div>
    @endif
 
    @if (session('success'))
        <div class="text-green-500 mb-2 text-center text-xl">{{ session('success') }}</div>
    @endif
 
     <form method="post" action="{{ route('password.update') }}" class="mt-6 space-y-6">
         @csrf
         @method('put')
 
         <div class="relative z-0 w-full mb-6 group">
             <input 
                 id="current_password" 
                 name="current_password" 
                 type="password" 
                 class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer @error('current_password') border-red-500 @enderror"    
                 required
                 />
             <label 
                 for="current_password" 
                 class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"  
             >
                 Mot de passe actuel
             </label>
 
             @error('current_password')
                 <div class="text-red-600 mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input 
                 id="password" 
                 name="password" 
                 type="password" 
                 class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer @error('password') border-red-500 @enderror" 
                 required
             />
             <label for="password" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Nouveau mot de passe
             </label>
             @error('password')
                 <div class="text-red-600 mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input 
                 id="password_confirmation" 
                 name="password_confirmation" 
                 type="password" 
                 class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                 required
             />
             <label for="password_confirmation" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Confirmation mot de passe
             </label>
             @error('password_confirmation')
                 <div class="text-red-600 mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="flex items-center gap-4">
             <x-primary-button>{{ __('Modifier') }}</x-primary-button>
 
             @if (session('status') === 'password-updated')
             <p x-data="{ show: true }" x-show="show" x-transition x-init="setTimeout(() => show = false, 2000)" class="text-sm text-gray-600 dark:text-gray-400">{{ __('Saved.') }}</p>
             @endif
         </div>
     </form>
 </section>