routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Cv\CvController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Offre\OffreController;
use App\Http\Controllers\Profile\ProfileController;
use App\Http\Controllers\Secteur\SecteurController;
use App\Http\Controllers\Candidat\CandidatController;
use App\Http\Controllers\Parametre\ParametreController;
use App\Http\Controllers\Recruteur\RecruteurController;
use App\Http\Controllers\Conversation\ConversationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'admin.auth.login')->name('login');
        Route::post('/check', [AdminController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:admin', 'PreventBackHistory'])->group(function () {

        Route::controller(OffreController::class)->group(function () {
            Route::get('/offres', 'index')->name('auth.offres');
            Route::get('/offres/favories', 'offresFavories')->name('auth.offres.favories');
            Route::get('/offres/mes-offres', 'mes_offres')->name('auth.offres.mes-offres');
            Route::get('/offres/create', 'create')->name('auth.offres.create');
            Route::post('/offres/store', 'store')->name('auth.offres.store');
            Route::get('/offres/{offre}/postulants', 'postulants')->name('auth.offres.postulants');
            Route::get('/offres/{offre}', 'show')->name('auth.offres.show');
            Route::put('/offres/{offre}', 'update')->name('auth.offres.update');
            Route::delete('/offres/{offre}', 'destroy')->name('auth.offres.destroy');
            Route::get('/offres/{offre}/edit', 'edit')->name('auth.offres.edit');
        });

        Route::controller(ConversationController::class)->group(function () {
            Route::get('/conversations', 'index')->name('auth.conversations');
            Route::get('/conversations/{conversation}', 'show')->name('auth.conversations.show');
        });

        Route::controller(SecteurController::class)->group(function () {
            Route::get('/secteurs', 'index')->name('auth.secteurs');
            Route::get('/secteurs/create', 'create')->name('auth.secteurs.create');
            Route::post('/secteurs/store', 'store')->name('auth.secteurs.store');
            Route::get('/secteurs/edit/{secteur}', 'edit')->name('auth.secteurs.edit');
            Route::put('/secteurs/update/{secteur}', 'update')->name('auth.secteurs.update');
            Route::delete('/secteurs/delete/{secteur}', 'destroy')->name('auth.secteurs.destroy');
        });

        Route::controller(CvController::class)->group(function () {
            Route::get('/cvs', 'index')->name('auth.cvs');
            Route::get('/cvs/create', 'create')->name('auth.cvs.create');
            Route::post('/cvs/store', 'store')->name('auth.cvs.store');
            Route::get('/cvs/show/{cv}', 'show')->name('auth.cvs.show');
            Route::delete('/cvs/delete{cv}', 'destroy')->name('auth.cvs.destroy');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });


        Route::controller(AdminController::class)->group(function() {
            Route::get('/candidats', 'candidats')->name('auth.candidats');
            Route::get('/recruteurs', 'recruteurs')->name('auth.recruteurs');
            Route::delete('/candidats/{user}', 'destroyUser')->name('auth.candidats.destroy');
            Route::delete('/recruteurs/{user}', 'destroyUser')->name('auth.recruteurs.destroy');
            // Route::get('/moi/profils', 'profils')->name('auth.profils');
            Route::post('/logout', 'logout')->name('auth.logout');
        });

        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

    });
});

Route::prefix('recruteur')->name('recruteur.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'recruteur.auth.login')->name('login');
        Route::view('/register', 'recruteur.auth.register')->name('register');
        Route::post('/register', [RecruteurController::class, 'storeRegister'])->name('store.register');
        Route::post('/check', [RecruteurController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:recruteur', 'PreventBackHistory'])->group(function () {

        Route::controller(OffreController::class)->group(function () {
            // Route::get('/offres', 'index')->name('auth.offres');
            // Route::get('/offres/favories', 'offresFavories')->name('auth.offres.favories');
            Route::get('/offres/mes-offres', 'mes_offres')->name('auth.offres.mes-offres');
            Route::get('/offres/create', 'create')->name('auth.offres.create');
            Route::post('/offres/store', 'store')->name('auth.offres.store');
            Route::get('/offres/{offre}/postulants', 'postulants')->name('auth.offres.postulants');
            Route::get('/offres/{offre}', 'show')->name('auth.offres.show');
            Route::put('/offres/{offre}', 'update')->name('auth.offres.update');
            Route::get('/offres/{offre}/edit', 'edit')->name('auth.offres.edit');
            Route::delete('/offres/{offre}', 'destroy')->name('auth.offres.destroy');
        });


        Route::controller(ConversationController::class)->group(function () {
            Route::get('/conversations', 'index')->name('auth.conversations');
            Route::get('/conversations/{conversation}', 'show')->name('auth.conversations.show');
        });

        Route::controller(CvController::class)->group(function () {
            Route::get('/cvs', 'index')->name('auth.cvs');
            Route::get('/cvs/create', 'create')->name('auth.cvs.create');
            Route::post('/cvs/store', 'store')->name('auth.cvs.store');
            Route::get('/cvs/show/{cv}', 'show')->name('auth.cvs.show');
            Route::delete('/cvs/delete{cv}', 'destroy')->name('auth.cvs.destroy');
        });


        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::patch('moi/profils/update-additional', 'updateAdditional')->name('auth.profils.updateAdditional');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });

        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::patch('moi/profils/update-additional', 'updateAdditional')->name('auth.profils.updateAdditional');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });

        Route::controller(RecruteurController::class)->group(function() {
            // Route::get('/moi/profils', 'profils')->name('auth.profils');
            // Route::get('/moi/parametres', 'parametres')->name('auth.parametres');
            Route::post('/logout', 'logout')->name('auth.logout');
        });
    });
});

Route::prefix('candidat')->name('candidat.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'candidat.auth.login')->name('login');
        Route::view('/register', 'candidat.auth.register')->name('register');
        Route::post('/register', [CandidatController::class, 'storeRegister'])->name('store.register');
        Route::post('/check', [CandidatController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:candidat', 'PreventBackHistory'])->group(function () {

resources/views/candidat/profil/partials/update-additional-information-form.blade.php
<section>

     <header>
          <h2 class="text-xl font-bold" id="additional-information">
               {{ __("Informations Supplémentaires") }}
           </h2>
     </header>
 
     <form class="mt-5" action="{{ route('candidat.auth.profils.updateAdditional') }}" method="POST" enctype="multipart/form-data">
         @csrf
         @method('patch')

         <div class="mb-6">
               <label for="cv" class="block font-semibold text-gray-700 mb-2">CV<span class="text-sm font-normal">(Image: jpeg, png, jpg, doc, docx, pdf)</span>:</label>
               <input type="file" name="cv" id="cv" class="form-control">
               @error('cv')
                    <span class="text-red-400 text-sm">{{ $message }}</span>
               @enderror
          </div>
 
         <div class="mb-4 grid grid-cols-1 md:grid-cols-2 gap-6">
              <div class="relative z-0 w-full mb-1">
                  <input type="text" name="profession" value="{{ auth()->user()->infoCandidat->profession }}" id="profession" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"  />
                  <label for="profession" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                      Profession
                  </label>
                  @error('profession')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                  @enderror
              </div>

              <div class="relative z-0 w-full mb-1">
                  <input type="text" name="formation" value="{{ auth()->user()->infoCandidat->formation }}" id="formation" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"  />
                  <label for="formation" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                      Formation
                  </label>
                  @error('formation')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                  @enderror
              </div>
         </div>

         <div class="mb-4 grid grid-cols-1 md:grid-cols-2 gap-6">
              <div class="relative z-0 w-full mb-1">
                  <input type="text" name="langue" value="{{ auth()->user()->infoCandidat->langue }}" id="langue" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"  />
                  <label for="langue" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                      Langue
                  </label>
                  @error('langue')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                  @enderror
              </div>

              <div class="relative z-0 w-full mb-1">
                  <input type="text" name="niveau_etude" value="{{ auth()->user()->infoCandidat->niveau_etude }}" id="niveau_etude" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"  />
                  <label for="niveau_etude" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                      Niveau d'étude
                  </label>
                  @error('niveau_etude')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                  @enderror
              </div>
         </div>

         <div class="mb-4">
               <div class="relative z-0 w-full mb-1">
                    <input type="text" name="competence" value="{{ auth()->user()->infoCandidat->competence }}" id="competence" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"  />
                    <label for="competence" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                         Competence
                    </label>
                    @error('competence')
                         <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                    @enderror
               </div>
         </div> 

         <div class="mb-4">
               <label for="motivation" class="block font-semibold text-gray-700 mb-2">Description de Vos motivations</label>
               <textarea 
                    name="motivation" 
                    id="motivation" 
                    class="shadow border rounded w-full text-xl" cols="30" rows="10"
               >
                    {!! old('motivation', auth()->user()->infoCandidat->motivation) !!}
               </textarea>
               @error('motivation')
                    <span class="text-red-400 text-sm">{{ $message }}</span>
               @enderror
          </div>

         <div class="mb-4">
               <label for="experience" class="block font-semibold text-gray-700 mb-2">Description de Vos expériences</label>
               <textarea 
                    name="experience" 
                    id="experience" 
                    class="shadow border rounded w-full text-xl" cols="30" rows="10"
               >
                    {!! old('experience', auth()->user()->infoCandidat->experience) !!}
               </textarea>
               @error('experience')
                    <span class="text-red-400 text-sm">{{ $message }}</span>
               @enderror
          </div>
 
         <button type="submit" class="bg-blue-500 text-white hover:bg-blue-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg py-1 px-3 text-white rounded uppercase my-4">Modifier</button>
         <button class="bg-red-500 text-white hover:bg-red-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg py-1 px-3 text-white rounded uppercase my-4">
             <a href="{{ route('recruteur.auth.profils') }}" enctype="multipart/form-data">
                 Annuler
             </a>
         </button>
 
     </form>
    
 </section>

 @push('scripts')
 <script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>
 <script>
     ClassicEditor
         .create( document.querySelector( '#motivation' ) )
         .catch( error => {
             console.error( error );
     } );

     ClassicEditor
         .create( document.querySelector( '#experience' ) )
         .catch( error => {
             console.error( error );
     } );
 </script>
@endpush

resources/views/candidat/profil/partials/update-personal-information-form.blade.php
<section>

     <header>
         <h2 class="text-xl font-bold" id="personal-information">
             {{ __("Informations Personnelles") }}
         </h2>
     </header>
 
     <form id="send-verification" method="post" action="{{ route('verification.send') }}">
         @csrf
     </form>
 
     <form class="mt-5" action="{{ route('candidat.auth.profils.update') }}" method="POST" enctype="multipart/form-data">
         @csrf
         @method('patch')
 
         <div class="mb-6">
             <label for="image">
                  Image CV <span class="text-sm font-normal">(Image: jpeg, png, jpg)</span> :
             </label>
             <input type="file" name="image" value="{{ old('image', auth()->user()->image) }}" id="image" />
             @error('image')
                  <div class="text-red-500 mt-1 mb-1">{{ $message }}</div>
             @enderror
        </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input type="text" name="nom" value="{{ auth()->user()->nom }}" id="nom" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
             <label for="nom" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Nom 
             </label>
             @error('nom')
             <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input type="text" name="prenom" value="{{ auth()->user()->prenom }}" id="prenom" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
             <label for="prenom" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Prenom
             </label>
             @error('prenom')
             <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input type="text" name="telephone" value="{{ auth()->user()->telephone }}" id="telephone" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
             <label for="telephone" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Téléphone de l'utilisateur
             </label>
             @error('telephone')
             <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input type="text" name="adresse" value="{{ auth()->user()->adresse }}" id="adresse" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
             <label for="adresse" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Adresse
             </label>
             @error('adresse')
             <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input type="text" name="ville" value="{{ auth()->user()->ville }}" id="ville" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
             <label for="ville" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Ville
             </label>
             @error('ville')
             <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
             @enderror
         </div>
 
         <div class="relative z-0 w-full mb-6 group">
             <input type="text" name="email" value="{{ auth()->user()->email }}" id="email" class="block py-2.5 px-0 w-full text-md text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
             <label for="email" class="peer-focus:font-medium absolute text-md text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                 Email
             </label>
             @error('email')
             <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
             @enderror
 
             @if (auth()->user() instanceof \Illuminate\Contracts\Auth\MustVerifyEmail && ! auth()->user()->hasVerifiedEmail())
             <div>
                 <p class="text-md mt-2 text-gray-800 dark:text-gray-200">
                     {{ __('Votre adresse e-mail n\'est pas vérifiée.') }}
 
                     <button form="send-verification" class="underline text-md text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">
                         {{ __('Cliquez ici pour renvoyer l\'e-mail de vérification.') }}
                     </button>
                 </p>
 
                 @if (session('status') === 'vérification-lien-envoyé')
                 <p class="mt-2 font-medium text-md text-green-600 dark:text-green-400">
                     {{ __('Un nouveau lien de vérification a été envoyé à votre adresse e-mail.') }}
                 </p>
                 @endif
             </div>
             @endif
         </div>
 
 
         <button type="submit" class="bg-blue-500 text-white hover:bg-blue-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg py-1 px-3 text-white rounded uppercase my-4">Modifier</button>
         <button class="bg-red-500 text-white hover:bg-red-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg py-1 px-3 text-white rounded uppercase my-4">
             <a class="" href="{{ route('candidat.auth.profils') }}" enctype="multipart/form-data">
                 Annuler
             </a>
         </button>
 
         @if (session('status') === 'profile-updated')
             <p x-data="{ show: true }" x-show="show" x-transition x-init="setTimeout(() => show = false, 2000)" class="text-md text-gray-600 dark:text-gray-400">{{ __('Succès du mis à jour.') }}</p>
             @endif
     </form>
 
 
    
 </section>