routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Cv\CvController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Offre\OffreController;
use App\Http\Controllers\Profile\ProfileController;
use App\Http\Controllers\Secteur\SecteurController;
use App\Http\Controllers\Candidat\CandidatController;
use App\Http\Controllers\Parametre\ParametreController;
use App\Http\Controllers\Recruteur\RecruteurController;
use App\Http\Controllers\Conversation\ConversationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'admin.auth.login')->name('login');
        Route::post('/check', [AdminController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:admin', 'PreventBackHistory'])->group(function () {

        Route::controller(OffreController::class)->group(function () {
            Route::get('/offres', 'index')->name('auth.offres');
            Route::get('/offres/favories', 'offresFavories')->name('auth.offres.favories');
            Route::get('/offres/mes-offres', 'mes_offres')->name('auth.offres.mes-offres');
            Route::get('/offres/create', 'create')->name('auth.offres.create');
            Route::post('/offres/store', 'store')->name('auth.offres.store');
            Route::get('/offres/{offre}/postulants', 'postulants')->name('auth.offres.postulants');
            Route::get('/offres/{offre}', 'show')->name('auth.offres.show');
            Route::put('/offres/{offre}', 'update')->name('auth.offres.update');
            Route::delete('/offres/{offre}', 'destroy')->name('auth.offres.destroy');
            Route::get('/offres/{offre}/edit', 'edit')->name('auth.offres.edit');
        });

        Route::controller(ConversationController::class)->group(function () {
            Route::get('/conversations', 'index')->name('auth.conversations');
            Route::get('/conversations/{conversation}', 'show')->name('auth.conversations.show');
        });

        Route::controller(SecteurController::class)->group(function () {
            Route::get('/secteurs', 'index')->name('auth.secteurs');
            Route::get('/secteurs/create', 'create')->name('auth.secteurs.create');
            Route::post('/secteurs/store', 'store')->name('auth.secteurs.store');
            Route::get('/secteurs/edit/{secteur}', 'edit')->name('auth.secteurs.edit');
            Route::put('/secteurs/update/{secteur}', 'update')->name('auth.secteurs.update');
            Route::delete('/secteurs/delete/{secteur}', 'destroy')->name('auth.secteurs.destroy');
        });

        Route::controller(CvController::class)->group(function () {
            Route::get('/cvs', 'index')->name('auth.cvs');
            Route::get('/cvs/create', 'create')->name('auth.cvs.create');
            Route::post('/cvs/store', 'store')->name('auth.cvs.store');
            Route::get('/cvs/show/{cv}', 'show')->name('auth.cvs.show');
            Route::delete('/cvs/delete{cv}', 'destroy')->name('auth.cvs.destroy');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });


        Route::controller(AdminController::class)->group(function() {
            Route::get('/candidats', 'candidats')->name('auth.candidats');
            Route::get('/recruteurs', 'recruteurs')->name('auth.recruteurs');
            Route::delete('/candidats/{user}', 'destroyUser')->name('auth.candidats.destroy');
            Route::delete('/recruteurs/{user}', 'destroyUser')->name('auth.recruteurs.destroy');
            // Route::get('/moi/profils', 'profils')->name('auth.profils');
            Route::post('/logout', 'logout')->name('auth.logout');
        });

        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

    });
});

Route::prefix('recruteur')->name('recruteur.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'recruteur.auth.login')->name('login');
        Route::view('/register', 'recruteur.auth.register')->name('register');
        Route::post('/register', [RecruteurController::class, 'storeRegister'])->name('store.register');
        Route::post('/check', [RecruteurController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:recruteur', 'PreventBackHistory'])->group(function () {

        Route::controller(OffreController::class)->group(function () {
            // Route::get('/offres', 'index')->name('auth.offres');
            // Route::get('/offres/favories', 'offresFavories')->name('auth.offres.favories');
            Route::get('/offres/mes-offres', 'mes_offres')->name('auth.offres.mes-offres');
            Route::get('/offres/create', 'create')->name('auth.offres.create');
            Route::post('/offres/store', 'store')->name('auth.offres.store');
            Route::get('/offres/{offre}/postulants', 'postulants')->name('auth.offres.postulants');
            Route::get('/offres/{offre}', 'show')->name('auth.offres.show');
            Route::put('/offres/{offre}', 'update')->name('auth.offres.update');
            Route::get('/offres/{offre}/edit', 'edit')->name('auth.offres.edit');
            Route::delete('/offres/{offre}', 'destroy')->name('auth.offres.destroy');
        });


        Route::controller(ConversationController::class)->group(function () {
            Route::get('/conversations', 'index')->name('auth.conversations');
            Route::get('/conversations/{conversation}', 'show')->name('auth.conversations.show');
        });

        Route::controller(CvController::class)->group(function () {
            Route::get('/cvs', 'index')->name('auth.cvs');
            Route::get('/cvs/create', 'create')->name('auth.cvs.create');
            Route::post('/cvs/store', 'store')->name('auth.cvs.store');
            Route::get('/cvs/show/{cv}', 'show')->name('auth.cvs.show');
            Route::delete('/cvs/delete{cv}', 'destroy')->name('auth.cvs.destroy');
        });


        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::patch('moi/profils/update-additional', 'updateAdditional')->name('auth.profils.updateAdditional');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });

        Route::controller(ProfileController::class)->group(function() {
            Route::get('/moi/profils', 'index')->name('auth.profils');
            Route::get('moi/profils/edit', 'edit')->name('auth.profils.edit');
            Route::patch('moi/profils/update', 'update')->name('auth.profils.update');
            Route::patch('moi/profils/update-additional', 'updateAdditional')->name('auth.profils.updateAdditional');
            Route::get('profils/user/{user}', 'userProfil')->name('auth.profils.userProfil');
        });

        Route::controller(ParametreController::class)->group(function() {
            Route::get('/moi/parametres', 'edit')->name('auth.parametres');
            Route::patch('/parametre', 'update')->name('parametre.update');
            Route::delete('/parametre', 'destroy')->name('parametre.destroy');
        });

        Route::controller(RecruteurController::class)->group(function() {
            // Route::get('/moi/profils', 'profils')->name('auth.profils');
            // Route::get('/moi/parametres', 'parametres')->name('auth.parametres');
            Route::post('/logout', 'logout')->name('auth.logout');
        });
    });
});

Route::prefix('candidat')->name('candidat.')->group(function () {

    Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
        Route::view('/login', 'candidat.auth.login')->name('login');
        Route::view('/register', 'candidat.auth.register')->name('register');
        Route::post('/register', [CandidatController::class, 'storeRegister'])->name('store.register');
        Route::post('/check', [CandidatController::class, 'checkLogin'])->name('check.login');
    });

    Route::middleware(['auth', 'auth-role:candidat', 'PreventBackHistory'])->group(function () {

app/Http/Controllers/Offre/OffreController.php
<?php

namespace App\Http\Controllers\Offre;

use App\Models\Offre;
use App\Models\Secteur;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class OffreController extends Controller
{
    public function index() 
    {
        $secteurs = Secteur::all();

        if (request()->routeIs('admin.auth.offres')) {
            return view('admin.offre.offres', compact('secteurs'));
        }

        if (request()->routeIs('recruteur.auth.offres')) {
            return view('recruteur.offre.offres', compact('secteurs'));
        }

        return view('candidat.offre.offres', compact('secteurs'));

    }

    public function guestShowOffer(Offre $offre) 
    {
        // s'il est connecté
        if (Auth::check()) {
            return redirect()->back();
        }
        return view('guest-offer', compact('offre'));
    }

    public function guestOffers() 
    {
        // s'il est connecté
        if (Auth::check()) {
            return redirect()->back();
        }
        $secteurs = Secteur::all();
        return view('guest-offers', compact('secteurs'));
    }

    public function create() 
    {
        $secteurs = Secteur::all();

        if (request()->routeIs('admin.auth.offres.create')) {
            return view('admin.offre.create', compact('secteurs'));
        }

        if (request()->routeIs('recruteur.auth.offres.create')) {
            return view('recruteur.offre.create', compact('secteurs'));
        }
    }
    
    public function postulants(Offre $offre)
    {
        
        return view('admin.offre.postulants', compact('offre'));
    }

    public function postulate(Offre $offre) 
    {
        Gate::authorize('postulate');

        /** @var \App\Models\User $user **/
        $user = Auth::user();
        
        $query = $user->candidatOffres()
        ->wherePivot('user_id', auth()->user()->id)
        ->wherePivot('offre_id', $offre->id)->get();

        if ($query->count() == 0) {
            $user->candidatOffres()->attach($offre->id, ['recruteur_id' => $offre->user_id]);
            return redirect()->route('candidat.auth.offres.postulated');
        }
        
        return redirect()->route('candidat.auth.offres.postulated');
    }

    public function cancel_offer(Offre $offre) 
    {

        /** @var \App\Models\User $user **/
        $user = Auth::user();
        
        $query = $user->candidatOffres()
        ->wherePivot('user_id', auth()->user()->id)
        ->wherePivot('offre_id', $offre->id)->get();

        if ($query->count() > 0) {
            $user->candidatOffres()->detach($offre->id);
            return redirect()->route('candidat.auth.offres.postulated')->with('success', 'Annulée avec succès');
        }

        
    }

    public function offer_postuled() 
    {   
        $secteurs = Secteur::all();
        return view('candidat.offre.offer_postulated', compact('secteurs'));
    }

    public function update(Request $request, Offre $offre) 
    {
        $request->validate([
            'type_poste' => 'required',
            'titre_poste' => 'required',
            'localisation_poste'=> 'required',
            'description'=> 'required',
            'secteurs'=> 'required|min:1',
        ]);

        
        $offre->type_poste = $request->type_poste;
        $offre->titre_poste = $request->titre_poste;
        $offre->localisation_poste = $request->localisation_poste;
        $offre->description = $request->description;
        if ($request->email_candidature) {
            $offre->email_candidature = $request->email_candidature; 
        }
        if ($request->salaire) {
            $offre->salaire = $request->salaire;
        }

        if ($offre->isDirty()) {
            $offre->save();
            $offre->secteurs()->sync($request->secteurs);
            
            return redirect()->route('admin.auth.offres.show', ['offre' => $offre->id])->with('success','L\' offre a été mis à jour avec succès');
        }

        if (request()->routeIs('recruteur.auth.offres.update')) {
            return redirect()->route('recruteur.auth.offres.show', ['offre' => $offre->id]);
        }

    }

    public function store(Request $request) 
    {
        $request->validate([
            'type_poste' => 'required',
            'titre_poste' => 'required',
            'localisation_poste'=> 'required',
            'description'=> 'required',
            'secteurs'=> 'required|min:1',
        ]);

        $offre = new Offre();
        $offre->user_id = auth()->user()->id;
        $offre->type_poste = $request->type_poste;
        $offre->titre_poste = $request->titre_poste;
        $offre->localisation_poste = $request->localisation_poste;
        $offre->description = $request->description;
        if ($request->email_candidature) {
            $offre->email_candidature = $request->email_candidature; 
        }
        if ($request->salaire) {
            $offre->salaire = $request->salaire;
        }

        $offre->save();

        $offre->secteurs()->attach($request->secteurs);

        return redirect()->route('admin.auth.offres')->with('success', 'Offre publiée avec succès');
    }

    public function show(Offre $offre) 
    {
        Gate::authorize('candidat-recruteur-admin-model', $offre);   

        if (request()->routeIs('admin.auth.offres.show')) {
            return view('admin.offre.show', compact('offre'));
        }

        if (request()->routeIs('recruteur.auth.offres.show')) {
            
            return view('recruteur.offre.show', compact('offre'));
        }

        return view('candidat.offre.show', compact('offre'));

    }


    public function edit(Offre $offre) 
    {
        Gate::authorize('mofify', $offre);

        $allSecteurs = Secteur::all();
        $secteurs = $offre->secteurs;

        if (request()->routeIs('admin.auth.offres.edit')) {
            return view('admin.offre.edit', compact('offre', 'allSecteurs', 'secteurs'));
        }

        if (request()->routeIs('recruteur.auth.offres.edit')) {
            return view('recruteur.offre.edit', compact('offre', 'allSecteurs', 'secteurs'));
        }
    }
    

    public function mes_offres() 
    {
        $secteurs = Secteur::all();
        if (request()->routeIs('admin.auth.offres.mes-offres')) {
            return view('admin.offre.mes-offres', compact('secteurs'));
        }

        if (request()->routeIs('recruteur.auth.offres.mes-offres')) {
            return view('recruteur.offre.mes-offres', compact('secteurs'));
        }

    }

    public function offresFavories() 
    {
        $secteurs = Secteur::all();
        if (request()->routeIs('admin.auth.offres.favories')) {
            return view('admin.offre.favories', compact('secteurs'));
        }

        if (request()->routeIs('recruteur.auth.offres.favories')) {
            return view('recruteur.offre.favories', compact('secteurs'));
        }

        return view('candidat.offre.favories', compact('secteurs'));
    }

    public function destroy(Offre $offre) 
    {
        $offre->delete();
        
        if (request()->routeIs('admin.auth.offres.destroy')) {
            return redirect()->route('admin.auth.offres');
        }
        if (request()->routeIs('recruteur.auth.offres.destroy')) {
            return redirect()->route('recruteur.auth.offres');
        }
    }
}

app/View/Components/Offres/ShowOffer.php
<?php

namespace App\View\Components\Offres;

use App\Models\Offre;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class ShowOffer extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
        public Offre $offre
    )
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.offres.show-offer');
    }
}

resources/views/admin/offre/create.blade.php
@extends('layout-main.auth-main')

@section('content')

<div class="container-auth container-auth--margin">
     <h1 class="mt-5 text-center underline mb-3 text-center text-2xl">Création d'Offres</h1>

     <form method="POST" action="{{ route('admin.auth.offres.store') }}" enctype="multipart/form-data">
          @csrf
      
          <x-offres.create-offer :$secteurs>

               <x-slot:link>
                    <a 
                         href="{{route('admin.auth.offres') }}" 
                         class="bg-red-500 text-white hover:bg-red-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg p-1 text-white rounded"
                    >
                         Annuler
                    </a>
               </x-slot>

          </x-offres.create-offer>
     </form>

</div>

@push('scripts')
     <script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>
     <script>
         ClassicEditor
             .create( document.querySelector( '#description_offre' ) )
             .catch( error => {
                 console.error( error );
             } );
     </script>
@endpush
@endsection

resources/views/admin/offre/edit.blade.php
@extends('layout-main.auth-main')

@section('content')

<div class="container-auth container-auth--margin">
     <h1 class="mt-5 text-center underline mb-3 text-center text-2xl">Modification d'Offres</h1>

     <form method="POST" action="{{ route('admin.auth.offres.update', ['offre' => $offre->id]) }}" enctype="multipart/form-data">
          @csrf
          @method('PUT')
          
          <x-offres.edit-offer :all-secteurs="$allSecteurs" :$offre :$secteurs>
               <x-slot:link>
                    <a 
                         href="{{route('admin.auth.offres') }}" 
                         class="bg-red-500 text-white hover:bg-red-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg p-1 text-white rounded"
                    >
                         Annuler
                    </a>
               </x-slot>
          </x-offres.edit-offer>
          
     </form>

</div>

@push('scripts')
     <script src="https://cdn.ckeditor.com/ckeditor5/37.1.0/classic/ckeditor.js"></script>
     <script>
         ClassicEditor
             .create( document.querySelector( '#description_offre' ) )
             .catch( error => {
                 console.error( error );
             } );
     </script>
@endpush
@endsection

resources/views/admin/offre/favories.blade.php
@extends('layout-main.auth-main')

@section('content')

<div class="container-auth container-auth--margin">

     @include('partials.add-offer-button')
     <h1 class="mt-5 text-center underline mb-3 text-2xl">Vos Offres Favories</h1>

     @livewire('offre.offre-favori', ['secteurs' => $secteurs ])
     
</div>
@endsection

resources/views/admin/offre/mes-offres.blade.php
@extends('layout-main.auth-main')

@section('content')

<div class="container-auth container-auth--margin">
     @if ($message = Session::get('success'))
     <div id="alert-border-3" class="flex p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-green-50 dark:text-green-400 dark:bg-gray-800 dark:border-green-800" role="alert">
          <svg class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
               <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
          </svg>
          <div class="ml-3 text-sm font-medium">
               {{ $message }}
          </div>
     </div>
     @endif

     @include('partials.add-offer-button')
     <h1 class="mt-5 text-center underline mb-3 text-2xl">Vos Offres</h1>

     @livewire('offre.mes-offres', ['secteurs' => $secteurs ])
</div>
@endsection

resources/views/admin/offre/offres.blade.php
@extends('layout-main.auth-main')

@section('content')

<div class="container-auth container-auth--margin">
     @if ($message = Session::get('success'))
     <div id="alert-border-3" class="flex p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-green-50 dark:text-green-400 dark:bg-gray-800 dark:border-green-800" role="alert">
          <svg class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
               <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
          </svg>
          <div class="ml-3 text-sm font-medium">
               {{ $message }}
          </div>
     </div>
     @endif

     @include('partials.add-offer-button')
     <h1 class="mt-5 text-center underline mb-3 text-2xl">Les Offres</h1>

     @livewire('offre.offre', ['secteurs' => $secteurs ])

</div>

@endsection

resources/views/admin/offre/postulants.blade.php
@extends('layout-main.auth-main')

@section('content')

<div class="container-auth container-auth--margin">

     @include('partials.add-offer-button')
     <h1 class="mt-5 font-bold mb-3 text-2xl">{{ $offre->titre_poste }}</h1>

     <div class="flex items-center mb-20">
          <div class="w-28 h-28">
               @if (optional($offre->user->infoRecruteur)->logo_entreprise)
                    <img class="w-full h-full" src="{{ $offre->user->infoRecruteur->logo_entreprise }}" alt="logo de l'entreprise">
               @else
                    <img class="w-full h-full" src="/logos/default.avif" alt="logo par defaut">
               @endif
          </div>
          <div class="ml-2">
               <p class="capitalize"><i class="fa-solid fa-location-dot mr-1 text-gray-500"></i>{{ $offre->localisation_poste }}</p>
               <p class="capitalize">
                    @foreach ($offre->secteurs as $secteur)
                         {{ $secteur->nom }},&nbsp;
                    @endforeach
               </p>
               <p class="uppercase">{{ $offre->type_poste }}</p>
          </div>
     </div>
     
     @livewire('offre.postulants', ['offre' => $offre])
</div>
@endsection

resources/views/admin/offre/show.blade.php
@extends('layout-main.auth-main')

@section('content')

<div class="container-auth container-auth--margin">
     @if ($message = Session::get('success'))
     <div id="alert-border-3" class="flex p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-green-50 dark:text-green-400 dark:bg-gray-800 dark:border-green-800" role="alert">
          <svg class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
               <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
          </svg>
          <div class="ml-3 text-sm font-medium">
               {{ $message }}
          </div>
     </div>
     @endif

     @include('partials.add-offer-button')
     <h1 class="mt-5 font-bold mb-3 text-2xl">{{ $offre->titre_poste }}</h1>
     <div class="flex items-center mb-20">
          <div class="w-28 h-28">
               @if (optional($offre->user->infoRecruteur)->logo_entreprise)
               <img class="w-full h-full" src="{{ $offre->user->infoRecruteur->logo_entreprise }}" alt="logo de l'entreprise">
               @else
               <img class="w-full h-full" src="/logos/default.avif" alt="logo par defaut">
               @endif
          </div>
          <div class="ml-2">
               <p class="capitalize"><i class="fa-solid fa-location-dot mr-1 text-gray-500"></i>{{ $offre->localisation_poste }}</p>
               <p class="capitalize">
                    @foreach ($offre->secteurs as $secteur)
                    {{ $secteur->nom }},&nbsp;
                    @endforeach
               </p>
               <p class="uppercase">{{ $offre->type_poste }}</p>
          </div>
     </div>

     <div class="mb-5">
          <hr>
          @if ($offre->site_candidature)
          <button class="bg-blue-500 text-white hover:bg-blue-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg p-1 text-white rounded uppercase my-4">
               <a href="{{ $offre->site_candidature }}">Postuler</a>
          </button>
          @else
          <button class="bg-blue-500 text-white hover:bg-blue-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg p-1 text-white rounded uppercase my-4">Postuler</button>
          @endif
          <hr>
     </div>
     @if (optional($offre->user->infoRecruteur)->description_entreprise)
     <h2 class="text-1xl font-bold">Description entreprise</h2>
     {!! optional($offre->user->infoRecruteur)->description_entreprise !!}
     <hr class="my-4">
     @endif

     {!! $offre->description !!}

     @if ($offre->salaire)
     <p class="mt-5">Salaire: {{ $offre->salaire }} FCFA</p>
     @endif



     @can('recruteur-admin-model', $offre)
     <div class="flex justify-around">

          @can('mofify', $offre)
          <button class="bg-blue-500 text-white hover:bg-blue-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg py-1 px-3 text-white rounded uppercase my-4" title="éditer">
               <a href="{{ route('admin.auth.offres.edit', ['offre' => $offre->id]) }}">
                    <i class="fa-solid fa-pen-to-square text-2xl"></i>
               </a>
          </button>
          @endcan

          <button class="bg-green-500 text-white hover:bg-green-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg py-1 px-3 text-white rounded uppercase my-4" title="voir les postulant de cette offre">
               <a href="{{ route('admin.auth.offres.postulants', ['offre' => $offre->id]) }}">
                    <i class="fa-solid fa-handshake text-2xl"></i>
               </a>
          </button>

          <form action="{{ route('admin.auth.offres.destroy', ['offre' => $offre->id]) }}" method="post">
               @csrf
               @method('DELETE')
               <button class="bg-red-500 text-white hover:bg-red-700 transition ease-in-out duration-500 rounded-md shadow-md text-lg py-1 px-3 text-white rounded uppercase my-4" title="supprimer">
                    <i class="fa-solid fa-trash"></i>
               </button>
          </form>
     </div>
     @endcan
</div>

@endsection